version: "3.11"

services:
  ane_db:
    container_name: "ane_db"
    image: mysql:8.0.27
    command: --authentication_policy=mysql_native_password
    volumes:
      - mysql_ane:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_ane
      MYSQL_DATABASE: ane
    ports:
      - "3310:3306"
  adminernode:
    image: adminer
    container_name: adminernode
    ports:
      - "8080:8080"

volumes:
  app:
  mysql_ane: